# TravisCI (https://travis-ci.org) configuration file
# https://docs.travis-ci.com/user/languages/python

language: python

sudo: true

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

addons:
  apt:
    sources:
    - deadsnakes
    
# python3-dbus doesn't have a pip package, so must install at system level
# can't just using python3-dbus system level apt package, because the python3 version at the system level is python 3.2
# can't use python 3.2, because argparse unit tests use subunit, which is available only in python 3.4 and up
# so - must install custom compiled python3-dbus
# https://abdealijk.wordpress.com/2015/06/09/python-dbus-and-continuous-integration/

before_install:
  - ./install-custom-dbus.sh

script:
  # compile all files - ensure that syntax is correct
  #- python -m compileall common common/test common/plugins qt4 qt4/plugins
  # run unit tests - ensure that functionality is correct
  - cd common && ./configure && make test-v
