# TravisCI (https://travis-ci.org) configuration file
# https://docs.travis-ci.com/user/languages/python

language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# python3-dbus doesn't have a pip package, so must install at system level
addons:
  apt:
    packages:
      - python3-dbus

# needed to ensure that python can see the dbus library installed at system level (since travis operates containerized)
virtualenv:
  system_site_packages: true

script:
  # compile all files - ensure that syntax is correct
  - python -m compileall common common/test common/plugins qt4 qt4/plugins
  # run unit tests - ensure that functionality is correct
  - cd common && ./configure && make test-v
